# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.webdriver',
        'selenium.webdriver.common',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.remote',
        'selenium.webdriver.remote.webdriver',
        'selenium.webdriver.remote.errorhandler',
        'selenium.webdriver.chromium',
        'selenium.webdriver.chromium.webdriver',
        'typer',
        'typer.core',
        'typer.main',
        'click',
        'click.core',
        'rich',
        'rich.console',
        'rich.table',
        'rich.text',
        'linkedin_api',
        'auth',
        'linkedin_wrapper',
        'commands',
        'commands.profile',
        'commands.feed',
        'commands.posts',
        'commands.connections',
        'commands.search',
        'commands.messaging',
        'commands.jobs',
        'commands.company',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='linkedin-cli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
